host: 0.0.0.0
port: 10001
mode: debug

log:
  level: debug
  log_file: app_log.json
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  user: root
  password: zhengmr0646
  host: 127.0.0.1
  port: 3306
  dbname: shop_user_srv
