mode: debug
port: 11001

log:
  level: debug
  log_file: user-web/app_log.json
  max_size: 200
  max_age: 30
  max_backups: 7
rpc:
  ip: 192.168.3.9
  port: 10001
jwt:
  signs_key: Hv:X}iHgXc7-G_g5Nr9uD:Ah.cev.?F%
  issuer: zz
