nacos:
  host: 127.0.0.1
  port: 8848

  NamespaceId: user
  TimeoutMs: 5000
  NotLoadCacheAtStart: true
  LogDir: nacos/log
  CacheDir: nacos/cache
  LogLevel: debug

  DataId: goods-server
  Group: dev
####### 下面的不需要了，全部从 nacos 读取

host: 192.168.3.9
# port: 10001 动态获取
mode: debug
name: goods-server

log:
  level: debug
  log_file: app_log.json
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  user: root
  password: zhengmr0646
  host: 127.0.0.1
  port: 3306
  dbname: shop_user_srv

consul:
  host: 192.168.3.9
  port: 8500
